---
version: "0.3.6"
slug: ps5_mqtt
name: PS5 MQTT
description: Control Sony PlayStation 5 devices via MQTT
url: https://github.com/FunkeyFlo/ps5-mqtt
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
host_network: true
map:
  - "share:rw"
  - "config:ro"
options:
  ps5_credentials:
  mqtt:
    host:
    port:
    user:
    pass:
schema:
  ps5_credentials: str
  mqtt:
    host: str
    port: port
    user: str
    pass: str
stdin: true