---
version: "0.2"
slug: ps5_mqtt
name: PS5 MQTT
description: Control Sony PlayStation 5 devices via MQTT
url: https://github.com/FunkeyFlo/ps5-mqtt
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
image: homeassistant/{arch}-addon-rpc_shutdown
options:
  mqtt:
    host:
    port:
    user:
    pass:
  ps5_credentials:
schema:
  ps5_credentials: str
  mqtt:
    host: str
    port: str
    user: str
    pass: str
startup: services
stdin: true
init: false