---
version: "0.4.3"
slug: ps5_mqtt
name: PS5 MQTT
description: Control Sony PlayStation 5 devices via MQTT
url: https://github.com/FunkeyFlo/ps5-mqtt
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
host_network: true
map:
  - "share:rw"
  - "config:ro"
options:
  ps5_credentials: "contents of your playactor credentials.json file..."
  mqtt:
    host:
    port:
    user:
    pass:
  logger: "*,-mqttjs*,-mqtt-packet*,-playactor:*,-@ha:state*,-@ha:ps5:poll*,-@ha:ps5:check*"
  device_check_interval: "1000"
schema:
  ps5_credentials: str
  mqtt:
    host: str
    port: port
    user: str
    pass: str
  logger: "str?"
  device_check_interval: "int(1000, 60000)"
stdin: true
# image: "ghcr.io/funkeyflo/{arch}-ps5-mqtt"