---
version: "0.1"
slug: ps5_mqtt
name: PS5 MQTT
description: Control Sony PlayStation 5 devices via MQTT
url: https://github.com/FunkeyFlo/ps5-mqtt
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
image: homeassistant/{arch}-addon-rpc_shutdown
options:
  computers:
    - address: 192.168.0.1
      alias: test-pc
      credentials: user%password
      delay: 0
      message:
        Home Assistant is shutting down this PC. This cannot be canceled. Please
        save your work!
schema:
  computers:
    - address: str
      alias: match(^[\w-]*$)
      credentials: match(^[^%]*(?:%[^%]*)?$)
      delay: int(0,600)?
      message: str?
startup: services
stdin: true
init: false