blank_issues_enabled: false
contact_links:
  - name: PS5-MQTT Community Support
    url: https://discord.gg/BnmvYHvz5N
    about: Something not clear or you need some help figuring stuff out? Ask the community!