version: "edge"
slug: ps5_mqtt_edge
name: PS5 MQTT - Edge
description: Development build of the PS5 MQTT add-on
url: https://github.com/FunkeyFlo/ps5-mqtt/tree/master/add-ons/ps5-mqtt-edge
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
services:
  - "mqtt:need"
boot: auto
host_network: true
ingress: true
ingress_port: 0
panel_icon: 'mdi:sony-playstation'
ports:
  8645/tcp: null
ports_description:
  8645/tcp: PS5 MQTT Web Interface
map:
  - "config:rw"
options:
  mqtt: {}
  logger: "@ha:ps5:*"
  device_check_interval: 5000
  device_discovery_interval: 60000
  include_ps4_devices: false
schema:
  mqtt:
    host: str?
    port: port?
    user: str?
    pass: str?
  logger: str?
  device_check_interval: int
  device_discovery_interval: int
  include_ps4_devices: bool
stdin: true
image: "ghcr.io/funkeyflo/ps5-mqtt/{arch}"
